### ISSUE TITLE
Пошёл нахуй

### ISSUE THREAD

**Issue by 141sh1** [degradka/8ball#1]
![IMG_20220214_220716-1-1-23](https://user-images.githubusercontent.com/66506310/157845244-145d6240-736a-47ce-8fac-61cd6ece2d22.png)

**Comment by 141sh1** [comment]
Извините. Открыл не в том репозитории. Писькапиуськ сис
![IMG_20220214_220716-1-1-4](https://user-images.githubusercontent.com/66506310/157845809-a876a7bd-b61e-4760-8c22-7c9f5d85be43.png)
![IMG_20220214_220716-1-1-5](https://user-images.githubusercontent.com/66506310/157845812-a47bd74f-ee17-43f8-bbf9-6129e660cba7.png)
![IMG_20220214_220716-1-1-3](https://user-images.githubusercontent.com/66506310/157845813-08ce8fdd-f53f-4c66-a4bb-740fcfffddfe.png)
![IMG_20220214_220716-1-1-1](https://user-images.githubusercontent.com/66506310/157845816-ee134c7e-f969-4629-a1e1-224de71c47f0.png)
![IMG_20220214_220716-1-1-9](https://user-images.githubusercontent.com/66506310/157845821-ff2dc7c1-7c7a-4ad1-9327-c005f08b493c.png)
![IMG_20220214_220716-1-1-2](https://user-images.githubusercontent.com/66506310/157845826-806d9ca8-175f-4e91-8632-7bba49367399.png)

> `c`

**Comment by 141sh1** [comment]
Ой

**Comment by 141sh1** [comment]
Прошу прощения за это. Сейчас закрою ой

**Comment by 141sh1** [comment]
![Без названия34_20220310213753](https://user-images.githubusercontent.com/66506310/157846277-9faa49d0-ea32-4d76-af2c-50c531e85314.png)

**Comment by 141sh1** [comment]
Я хотел бы стать контрибутором как

**Comment by 141sh1** [comment]
Пожалуйста

**Comment by 141sh1** [comment]
@degradka

**Comment by 141sh1** [comment]
![Uploading IMG_20220214_220716-1-1-23.png…]()

**Comment by 141sh1** [comment]
Блять как удалить

**Comment by degradka** [comment]
@141sh1 свайпни влево

**Comment by 141sh1** [comment]
Спасибо
